litellm-url: 'https://iapi.makespacemadrid.org'
llm-model: 'vicuna:13b-v1.5'
spring:
  # sql:
  #   init:
      # mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: drop-and-create
              append: false
              create-target: src/main/resources/schema.sql
              drop-target: src/main/resources/schema_drop.sql
              sql-load-target: src/main/resources/data.sql
            create-source: metadata
  thymeleaf:
    prefix: 'classpath:/templates/'
  rabbitmq:
    host: localhost
    port: '5672'
    username: guest
    password: guest
