create sequence article_seq start with 1 increment by 50;
create sequence bulletin_seq start with 1 increment by 50;
create sequence cured_article_seq start with 1 increment by 50;
create sequence feed_seq start with 1 increment by 50;
create table article (published_at date, cured_article_id bigint, feed_id bigint, id bigint not null, full_content varchar(255), summary_content varchar(255), title varchar(255), url varchar(255), primary key (id));
create table bulletin (generation_completed_at date, generation_started_at date, published_at date, id bigint not null, primary key (id));
create table cured_article (published_at date, bulletin_id bigint, id bigint not null, content varchar(255), title varchar(255), primary key (id));
create table feed (id bigint not null, title varchar(255), url varchar(255), primary key (id));
alter table if exists article add constraint FK4uipg5rdpg6pw3taao04erajk foreign key (cured_article_id) references cured_article;
alter table if exists article add constraint FKqft6wk7f6tx6mvm9h6ssa4ea1 foreign key (feed_id) references feed;
alter table if exists cured_article add constraint FKganv6oqhbajktghfmbcui83je foreign key (bulletin_id) references bulletin;
