alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
alter table if exists article drop constraint if exists FK4uipg5rdpg6pw3taao04erajk;
alter table if exists article drop constraint if exists FKqft6wk7f6tx6mvm9h6ssa4ea1;
alter table if exists cured_article drop constraint if exists FKganv6oqhbajktghfmbcui83je;
alter table if exists cured_articles_tags drop constraint if exists FK61nwmp0ngr9si76jq9qnrhc99;
alter table if exists cured_articles_tags drop constraint if exists FKaty8wq2sy1f3uf61hm1i0wsfb;
drop table if exists article cascade;
drop table if exists bulletin cascade;
drop table if exists cured_article cascade;
drop table if exists cured_articles_tags cascade;
drop table if exists feed cascade;
drop table if exists job cascade;
drop table if exists tag cascade;
drop sequence if exists article_seq;
drop sequence if exists bulletin_seq;
drop sequence if exists cured_article_seq;
drop sequence if exists feed_seq;
drop sequence if exists job_seq;
drop sequence if exists tag_seq;
